# Generated by Django 5.1.6 on 2025-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название предмета")),
                ("description", models.TextField(verbose_name="Описание предмета")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена предмета")),
                (
                    "currency",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                        default="RUB",
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
                "ordering": ("-id",),
            },
        ),
    ]
